services:
  postgres:
    image: postgres:latest
    container_name: postgres-stock
    environment:
      POSTGRES_DB: stock
      POSTGRES_USER: user_stock
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
